{% set name = "protlearn" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: db3145ff28a4d82ae8f610bef06bed47a9a118f02188b02bf73ed3587dcf53a7
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pandas
    - scikit-learn
    - xgboost
    - mlxtend
    - biopython

test:
  imports:
    - protlearn
    - protlearn.dimreduction

about:
  home: https://github.com/tadorfer/protlearn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for extracting protein sequence features

  doc_url: https://protlearn.readthedocs.io/en/latest/
  dev_url: https://github.com/tadorfer/protlearn

extra:
  recipe-maintainers:
    - tadorfer
